on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.17.x]
        venv: [windows-2016, windows-2019, windows-2022]
    runs-on: ${{ matrix.venv }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run Test - Build
      run: go test -v ./...