on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.16.x, 1.17.x, 1.18.x]
        venv: [windows-2019, windows-2022]
        fips: [1, 0]
    runs-on: ${{ matrix.venv }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set FIPS mode
      run: REG ADD HKLM\SYSTEM\CurrentControlSet\Control\Lsa\FipsAlgorithmPolicy /v Enabled /t REG_DWORD /f /d ${{ matrix.fips }}
    - name: Run Test - Build
      run: go test -v -gcflags=all=-d=checkptr ./...
      env:
        GO_TEST_FIPS: ${{ matrix.fips }}